#!/bin/bash

ARGC=$#
MIN_ARGC="3"

if [ $ARGC -ne $MIN_ARGC ]; then
    echo Expected 3 arguments, how many times to run and min and max.
    exit;
fi

total=0
for (( i=1; i<=$1; i++ ))
do
    total=$((total + $(./test $2 $3 | grep Total | awk '{print $2}')))
done

echo "avg of $1 tests between $2 and $3" >> avgs
echo $(($total / $1)) >> avgs